" ----------------------------------------------------------------------------
" Project: dotvim
" Program: vimrc
" Purpose: Vim settings
" Version: 0.4.0
" Updated: Thu Dec 17 11:58:52 EST 2015
" Author:  Mauricio Caceres <mauricio.caceres.bravo@gmail.com>
" Inputs:
"       ~/.vim/undo
"       ~/.vim/spell
"       ~/.vim/session
"       ~/.vim/bundle
"       ~/Documents/projects/code/dotvim/dotvimrc/mappings.vim
"       ~/Documents/projects/code/dotvim/dotvimrc/fonts.vim
"       ~/Documents/projects/code/dotvim/dotvimrc/functions.vim
"       ~/Documents/projects/code/dotvim/dotvimrc/plugins.vim
"       ~/Documents/projects/code/dotvim/colors/mycolors.vim

" Startup: Load plug-ins {{{1
" ---------------------------

" Start: Start Vundle {{{2
filetype off
set nocompatible
set runtimepath+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

" Essential: 'Core' functionality; my most used {{{2
Plugin 'tpope/vim-repeat',          {'name' : 'repeat'}
Plugin 'tpope/vim-speeddating',     {'name' : 'speeddating'}
Plugin 'tpope/vim-surround',        {'name' : 'surround'}
Plugin 'tommcdo/vim-exchange',      {'name' : 'exchange'}
Plugin 'godlygeek/tabular',         {'name' : 'tabular'}
Plugin 'salsifis/vim-transpose',    {'name' : 'transpose'}
Plugin 'tomtom/tcomment_vim',       {'name' : 'tcomment'}
Plugin 'SirVer/ultisnips',          {'name' : 'ultisnips'}
Plugin 'mbbill/undotree',           {'name' : 'undotree'}
Plugin 'scrooloose/nerdtree',       {'name' : 'nerdtree'}
Plugin 'mhinz/vim-startify',        {'name' : 'startify'}
Plugin 'bling/vim-airline',         {'name' : 'airline'}
Plugin 'honza/vim-snippets',        {'name' : 'snippets'}
Plugin 'kien/ctrlp.vim',            {'name' : 'ctrlp'}

" Harmless: Oft useful but used scarcely {{{2
Plugin 'tpope/vim-unimpaired',      {'name' : 'unimpaired'}
Plugin 'tpope/vim-characterize',    {'name' : 'characterize'}
Plugin 'tpope/vim-fugitive',        {'name' : 'fugitive'}
Plugin 'airblade/vim-gitgutter',    {'name' : 'gitgutter'}
Plugin 'gregsexton/gitv',           {'name' : 'gitv'}
Plugin 'ervandew/screen',           {'name' : 'screen'}
Plugin 'flazz/vim-colorschemes',    {'name' : 'colorschemes'}
Plugin 'lilydjwg/colorizer',        {'name' : 'colorizer'}

" Testing: Plug-ins that I'm not all-in on yet {{{3

" Complex/conflicting to some degree
Plugin 'easymotion/vim-easymotion', {'name' : 'easymotion'}
Plugin 'Valloric/YouCompleteMe',    {'name' : 'YouCompleteMe'}
Plugin 'scrooloose/syntastic',      {'name' : 'syntastic'}
Plugin 'nvie/vim-flake8',           {'name' : 'flake8'}
Plugin 'tmhedberg/SimpylFold',      {'name' : 'simpylfold'}
Plugin 'vim-scripts/indentpython.vim', {'name' : 'indentpython'}

" Language support
" Plugin 'jpitblado/vim-stata',       {'name' : 'stata'}
" Plugin 'jpitblado/vim-smcl',        {'name' : 'smcl'}
Plugin 'JuliaLang/julia-vim',       {'name' : 'julia'}
Plugin 'jcfaria/Vim-R-plugin',      {'name' : 'rplugin'}
Plugin 'adimit/prolog.vim',         {'name' : 'prolog'}
Plugin 'suan/vim-instant-markdown', {'name' : 'instant-markdown'}
Plugin 'LaTeX-Box-Team/LaTeX-Box',  {'name' : 'latex-box'}
Plugin 'file:///home/mauricio/Documents/projects/code/dotvim/bundle/latex-suite-abridged'

" Unite (LOOKS veritably amazing but seems really slow)
" Plugin 'Shougo/neocomplete.vim',           {'name' : 'neocomplete'}
" Plugin 'Shougo/unite.vim',                 {'name' : 'unite'}
" Plugin 'Shougo/neomru.vim',                {'autoload' : {'unite_sources' : 'file_mru'}}
" Plugin 'osyo-manga/unite-airline_themes',  {'autoload' : {'unite_sources' : 'airline_themes'}}
" Plugin 'ujihisa/unite-colorscheme',        {'autoload' : {'unite_sources' : 'colorscheme'}}
" Plugin 'tsukkee/unite-tag',                {'autoload' : {'unite_sources' : ['tag', 'tag/file']}}
" Plugin 'Shougo/unite-outline',             {'autoload' : {'unite_sources' : 'outline'}}
" Plugin 'Shougo/unite-help',                {'autoload' : {'unite_sources' : 'help'}}
" Plugin 'Shougo/junkfile.vim',              {'autoload' : {'commands' : 'JunkfileOpen', 'unite_sources' : ['junkfile',  'junkfile/new']}}

" End: End Vundle {{{2
call vundle#end()
filetype plugin indent on
syntax enable

" Options: Vim options I like {{{1
" --------------------------------

" Essential: Some options to make Vim behave more sanely {{{2

set autoindent lazyredraw ruler showcmd number
set ignorecase smartcase smarttab
set autochdir autoread noswapfile
set wildmenu wildchar=<Tab>
set cryptmethod=blowfish2
set backspace=indent,eol,start
set winaltkeys=no
set splitright

" Preferences: Some personal tweaks {{{2

" Map leaders
let maplocalleader = "\\"
let mapleader = ","

" Remove octal from number formats
set nrformats-=octal

" Set up completion and dictionary
" set complete=.,w,b,u,t,i,d,k/home/mauricio/.vim/spell/en.utf-8.add

" Make sure we are doing utf8
if &encoding ==# 'latin1' && has('gui_running')
    set encoding=utf-8 ambiwidth=double
endif

" Remember more history
if &undoreload < 10000
    set undoreload=10000
endif
if &undolevels < 1024
    set undolevels=1024
endif
if &history < 1024
    set history=1024
endif
if &tabpagemax < 42
    set tabpagemax=42
endif

" Use persistent undo
if has("persistent_undo")
    set undodir=$HOME/.vim/undo
    set undofile
endif

" Use par for hard-wrapping text (requires par)
if executable('par')
    set formatprg=par\ -w72req
endif

" Aesthetics: Personally preferred aesthetics {{{2

" Always show status line
" Cursor 4 lines off scrolling
" Minimal GUI
set laststatus=2 scrolloff=2 guioptions=aegtr

" Set all tabs to 4 characters, expand tabs to spaces
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab

" Highlight search words
" Incremental search highlights
" Highlight current line
" Highlight textwidth column
set incsearch hlsearch cursorline colorcolumn=

" Set spelling, undercurl words not in dictionary
set spell
hi clear SpellBad
hi SpellBad cterm=underline ctermfg=red gui=undercurl

" Set soft wrap and soft-wrap toggle
" Set soft wrap hanging line character
set showbreak=\ \ 
set wrap linebreak nolist breakindent
command! -nargs=* Wrap set wrap linebreak nolist
command! -nargs=* Nowrap set nowrap nolinebreak

" Change grayness of comments of the fly, set it to 42
command! -nargs=1 Setgray hi Comment cterm=italic gui=italic guifg=grey<args>

" Source Files: mappings, fonts, options, etc. {{{1
"--------------------------------------------------

source $HOME/Documents/projects/code/dotvim/dotvimrc/mappings.vim
source $HOME/Documents/projects/code/dotvim/dotvimrc/functions.vim
source $HOME/Documents/projects/code/dotvim/colors/mycolors.vim
source $HOME/Documents/projects/code/dotvim/dotvimrc/fonts.vim
source $HOME/Documents/projects/code/dotvim/dotvimrc/plugins.vim

" Modelines: Fold this file {{{1
" vim: nowrap fdm=marker
" }}}
